### ISSUE TITLE
Can't fetch usergroups on front

### ISSUE THREAD

**Issue by dawidzebacki** [EscolaLMS/Admin#158]
![Zrzut ekranu z 2021-09-27 10-12-11](https://user-images.githubusercontent.com/64470068/134869899-5f285911-8b33-42a4-a78b-aa8b06b6b0ae.png)

**Comment by dawidzebacki** [comment]
```json
Object { loading: false, error: ResponseError }
​
error: ResponseError: http error
​​
columnNumber: 21
​​
data: "<!doctype html>\n<html class=\"theme-light\">\n<!--\nSymfony\\Component\\Routing\\Exception\\RouteNotFoundException: Route [login] not defined. in file /var/www/escola-lms-api/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 444\n\n#0 /var/www/escola-lms-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(726): Illuminate\\Routing\\UrlGenerator-&gt;route('login', Array, true)\n#1 /var/www/escola-lms-api/app/Http/Middleware/Authenticate.php(18): route('login')\n#2 /var/www/escola-lms-api/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(83): App\\Http\\Middleware\\Authenticate-&gt;redirectTo(Object(Illuminate\\Http\\Request))\n#3 /var/www/escola-lms-api/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(68): Illuminate\\Auth\\Middleware\\Authenticate-&gt;unauthenticated(Object(Illuminate\\Http\\Request), Array)\n#4 /var/www/escola-lms-api/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(42): Illuminate\\Auth…"
​​
fileName: "http://localhost:3000/static/js/vendors~main.chunk.js"
​​
lineNumber: 251362
​​
message: "http error"
​​
name: "ResponseError"
​​
request: Object { url: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups", options: {…}, originUrl: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups" }
​​​
options: Object { method: "GET", useCache: true, url: "/api/admin/user-groups", … }
​​​​
credentials: "same-origin"
​​​​
headers: Object {  }
​​​​​
<prototype>: Object { … }
​​​​
interceptors: true
​​​​
method: "GET"
​​​​
params: Object { pageSize: undefined, current: undefined, per_page: undefined, … }
​​​​​
current: undefined
​​​​​
page: undefined
​​​​​
pageSize: undefined
​​​​​
per_page: undefined
​​​​​
<prototype>: Object { … }
​​​​
url: "/api/admin/user-groups"
​​​​
useCache: true
​​​​
<prototype>: Object { … }
​​​
originUrl: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups"
​​​
url: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups"
​​​
<prototype>: Object { … }
​​
response: Response { useCache: false, type: "cors", url: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups", … }
​​​
body: ReadableStream { locked: false }
​​​​
locked: false
​​​​
<prototype>: ReadableStream.prototype { cancel: cancel(), getReader: getReader(), tee: tee(), … }
​​​
bodyUsed: false
​​​
headers: Headers {  }
​​​​
<prototype>: HeadersPrototype { append: append(), delete: delete(), get: get(), … }
​​​
ok: false
​​​
redirected: false
​​​
status: 500
​​​
statusText: "Internal Server Error"
​​​
type: "cors"
​​​
url: "https://escola-lms-api.stage.etd24.pl/api/admin/user-groups"
​​​
useCache: false
​​​
<prototype>: ResponsePrototype { clone: clone(), arrayBuffer: arrayBuffer(), blob: blob(), … }
​​
stack: "_construct@http://localhost:3000/static/js/vendors~main.chunk.js:251362:21\nWrapper@http://localhost:3000/static/js/vendors~main.chunk.js:251386:14\n_createSuperInternal@http://localhost:3000/static/js/vendors~main.chunk.js:251431:24\nResponseError@http://localhost:3000/static/js/vendors~main.chunk.js:251689:22\nparseResponseMiddleware/<@http://localhost:3000/static/js/vendors~main.chunk.js:252049:11\n"
​​
type: "HttpError"
​​
<prototype>: Object { stack: "", … }
​
loading: false
​
<prototype>: Object { … }
```
